### ISSUE TITLE
Possible Typo in color code documentation

### ISSUE THREAD

**Issue by demongund** [LordAshes/TaleSpire-StatesPlugin#1]
The walkthrough document has a demo file with color codes which are # + 6 character long. 
{
    "Poisoned": "<#00FF00>Poisoned<Default>",
    "Frozen": "<#FFFFFF>Frozen<Default>",
    "Shocked": "<#5555FF>Shocked<Default>",
    "Exhausted": "<#FF7733>Exhausted<Default>",
    "On Fire": "<#FF0000>Exhausted<Default>",
    "<Default>": "<#000000>"
}

But the color schema DESCRIPTIONS says it must be: #RRGGBBAA ( # + 6 characters long).

Also, the entries for Exhausted and On Fire both read 'exhausted' in the replacement text.

Unless I'm reading it wrong, there might be a typo in there somewhere!

**Comment by LordAshes** [comment]
The color codes used in the JSON file and manual entry can be hash plus 6
digit (RRGGBB) or 8 digits (RRGGBBAA). If hash plus 6 digits are used then
the AA (alpha) is assumed to be FF.

The base color in the R2ModMan may support both formats too but I have not
tested that.

Best Regards,

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
Document updated to explain this a bit better.
