### ISSUE TITLE
Color code file not being honored?

### ISSUE THREAD

**Issue by demongund** [LordAshes/TaleSpire-StatesPlugin#2]
I followed the instructions and placed the attached file in the following location - 

SteamLibrary\steamapps\common\TaleSpire\TaleSpire_CustomData\Config

I then used Ctrl + S to open the dialog, typed in On Fire and the text was not colorized.

I tested manual colorization and it worked just fine.

![image](https://user-images.githubusercontent.com/25164882/120427398-b226e880-c326-11eb-8860-08e4c1bb1b8c.png)

**Comment by LordAshes** [comment]
You wrote that you placed the file in:


*SteamLibrary\steamapps\common\TaleSpire\TaleSpire_CustomData\Config*

If that is the case then it is in the wrong folder. The correct folder
should be:


*SteamLibrary\steamapps\common\TaleSpire\TaleSpire_CustomData\Config\org.lordashes.plugins.states*

(The "org.lordashes.plugins.states" is part of the folder)

With a file name, as per the Read Me file, of *ColorizedKeywords.json*

So the file path and name should be:

*SteamLibrary\steamapps\common\TaleSpire\TaleSpire_CustomData\Config\org.lordashes.plugins.states\ColorizedKeywords.json*

Sorry for the confusion but, I believe, the Read Me file does say this if
you read it carefully :D

Best Regards,

Lord Ashes



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by LordAshes** [comment]
I should have included the sample file in the plugin so that it would have
been obvious. I was going to do this but I forgot to include it when I
packaged it up.

Best Regards,

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by demongund** [comment]
Okay, I'll try again with that being a folder! In general, a folder with periods like that is definitely not something a normal user would recognize as a folder.

It might be easier to read if you have the whole section read - 'The JSON file is expected to be at...'

\Steam\steamapps\common\TaleSpire\TaleSpire_CustomData\Config\org.lordashes.plugins.states\ColorizedKeywords.json

This makes sense especially if they can't change the name of the colorization file.

Thanks again for the AWESOME plugin!

**Comment by LordAshes** [comment]
Thanks for the suggestions. If the plugin needs an update I will take the
opportunity to also reword the documentation. I don't want to up-rev the
plugin just for documentation changes.

Best Regards,

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by demongund** [comment]
Tested and works great!
