### ISSUE TITLE
States visible when a mini is out of a character's field of vision

### ISSUE THREAD

**Issue by PyroGH** [LordAshes/TaleSpire-StatesPlugin#5]
![States](https://user-images.githubusercontent.com/45740751/180617751-6913c192-c3b8-4b87-b95b-5c7ebf316d05.png)

**Comment by LordAshes** [comment]
That is as designed. If you want hidden states use the GM Notes plugin
instead.

Best Regards,

Lord Ashes

**Comment by PyroGH** [comment]
Oh, that's great, thank you for your answer :)
